### ISSUE TITLE
Macrobenchmark test sample fails

### ISSUE THREAD

**Issue by Nikron9** [android/performance-samples#105]
After starting tests:

```Task :macrobenchmark:connectedReleaseAndroidTest
Starting 5 tests on Hammer_IRON_3_LTE - 9

com.example.macrobenchmark.SmallListStartupBenchmark > startup[mode=COLD][Hammer_IRON_3_LTE - 9] FAILED 
        java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at androidx.benchmark.macro.perfetto.StartupTimingQuery.findEndRenderTimeForUiFrame(StartupTimingQuery.kt:202)

com.example.macrobenchmark.TrivialStartupBenchmark > startup[mode=COLD][Hammer_IRON_3_LTE - 9] FAILED 
        java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at androidx.benchmark.macro.perfetto.StartupTimingQuery.findEndRenderTimeForUiFrame(StartupTimingQuery.kt:202)

[Device]: Error during Sync: Remote object doesn't exist!
````

```Task :macrobenchmark:connectedReleaseAndroidTest
Error while pulling test data from device.
java.io.IOException: Failed to pull \storage\emulated\0\Android\data\com.example.macrobenchmark.target\files\test_data\SmallListStartupBenchmark_startup[mode=COLD]_iter000_2022-01-11-18-57-13.perfetto-trace from device
        at com.android.build.gradle.internal.testing.ConnectedDevice.pullFile(ConnectedDevice.java:212)
        at com.android.build.gradle.internal.testing.SimpleTestRunnable$3.processNewLines(SimpleTestRunnable.java:448)
        at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:104)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:706)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:470)
        at com.android.ddmlib.internal.DeviceImpl.executeShellCommand(DeviceImpl.java:708)
        at com.android.build.gradle.internal.testing.ConnectedDevice.executeShellCommand(ConnectedDevice.java:180)
        at com.android.build.gradle.internal.testing.SimpleTestRunnable.executeShellCommand(SimpleTestRunnable.java:550)
        at com.android.build.gradle.internal.testing.SimpleTestRunnable.pullTestData(SimpleTestRunnable.java:468)
        at com.android.build.gradle.internal.testing.SimpleTestRunnable.run(SimpleTestRunnable.java:258)
        at com.android.build.gradle.internal.tasks.Workers$ProfileAwareExecutorServiceAdapter$submit$submission$1.run(Workers.kt:165)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1406)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.android.ddmlib.SyncException: Remote object doesn't exist!
        at com.android.ddmlib.SyncService.pullFile(SyncService.java:341)
        at com.android.ddmlib.internal.DeviceImpl.pullFile(DeviceImpl.java:1079)
        at com.android.build.gradle.internal.testing.ConnectedDevice.pullFile(ConnectedDevice.java:205)
        ... 16 more
````

Build environment:

Hammer Iron 3 LTE - Android 10 - API 28
Android Studio version: Arctic Fox | 2020.3.1 Patch 2
Android Build Tools version: 30.0.2
Gradle version: 7.0.4

**Comment by keyboardsurfer** [comment]
Do you have a way to run the tests again on a device with `adb root` and API level 29+?

**Comment by Nikron9** [comment]
Fixed in newest version of library 😄
