### ISSUE TITLE
Unable to target the another package with in the project 

### ISSUE THREAD

**Issue by PrateekChaurasia** [android/performance-samples#131]
java.lang.AssertionError: Unable to find target package org.view.activity, is it installed?
	at androidx.benchmark.macro.MacrobenchmarkKt.checkErrors(Macrobenchmark.kt:48)
	at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmark(Macrobenchmark.kt:126)
	at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmarkWithStartupMode(Macrobenchmark.kt:301)
	at androidx.benchmark.macro.junit4.MacrobenchmarkRule.measureRepeated(MacrobenchmarkRule.kt:102)
	at androidx.benchmark.macro.junit4.MacrobenchmarkRule.measureRepeated$default(MacrobenchmarkRule.kt:92)
	at com.ril.benchmark.VidyoActivityBenchmark.nonExportedActivityScrollList(ActivityBenchmark.kt:32)
	... 34 trimmed
Caused by: android.content.pm.PackageManager$NameNotFoundException: org.jio.meet.conference.view.activity
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:452)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:441)
	at androidx.benchmark.macro.MacrobenchmarkKt.checkErrors(Macrobenchmark.kt:46)

**Comment by keyboardsurfer** [comment]
This is an issue with modifications you made to the sample rather than with the sample itself.
Please make sure to provide the right package name for the application that's being benchmarked.
