### ISSUE TITLE
Macrobenchmark was crashed with following log

### ISSUE THREAD

**Issue by ganadist** [android/performance-samples#162]
Tested version : [79a9e78](https://github.com/android/performance-samples/commit/79a9e7875fe351c4c67a066be1c5fe97130c5e4e)
Tested devices :
  * Galaxy Fold Z 3 / Android 12 : samsung/q2qksx/qssi:12/SP1A.210812.016/F926NKSU1CVEE:user/release-keys
  * Xiaomi A1 / Android 9 : xiaomi/tissot/tissot_sprout:9/PKQ1.180917.001/V10.0.11.0.PDHMIXM:user/release-keys

Crash log:
```
 E AndroidRuntime: Process: com.example.macrobenchmark.target, PID: 10399
 E AndroidRuntime: java.lang.IllegalAccessError: Method 'int android.view.View.getWindowAttachCount()' is inaccessible to class 'android.view.ViewSpyInternalKt' (declaration of 'android.view.ViewSpyInternalKt' appears in /data/app/com.example.macrobenchmark.target-rAmBOWYiDAmM_yXDt20HxQ==/base.apk)
 E AndroidRuntime: 	at android.view.ViewSpyInternalKt.windowAttachCount(ViewSpyInternal.kt:7)
 E AndroidRuntime: 	at com.example.macrobenchmark.target.ClickTrace$install$1.onRootViewAdded(ClickTrace.kt:7)
 E AndroidRuntime: 	at com.example.macrobenchmark.target.ClickTrace$install$1.onRootViewsChanged(ClickTrace.kt:7)
 E AndroidRuntime: 	at curtains.internal.RootViewsSpy$delegatingViewList$1.add(RootViewsSpy.kt:28)
 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:350)
 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3880)

```

**Comment by mlykotom** [comment]
Thanks for the report!

The problem is because the method is stripped from the app after R8 optimization. I've forwarded the issue https://github.com/square/curtains/issues/36 

In the meanwhile, we'll add the rule to keep the method so it doesn't crash.
