### ISSUE TITLE
java.lang.IllegalStateException: Unable to acquire intent for package com.xxx

### ISSUE THREAD

**Issue by kongxiaoan** [android/performance-samples#171]
java.lang.IllegalStateException: Unable to acquire intent for package com.xxx
	at androidx.benchmark.macro.MacrobenchmarkScope.startActivityAndWait(MacrobenchmarkScope.kt:85)
	at androidx.benchmark.macro.MacrobenchmarkScope.startActivityAndWait$default(MacrobenchmarkScope.kt:81)

**Comment by keyboardsurfer** [comment]
Thank you for reporting this issue. The information provided is not enough for us to  investigate the problem you are facing. Please provide information that can help us reproduce it.
