### ISSUE TITLE
java.io.FileNotFoundException - perfetto-trace

### ISSUE THREAD

**Issue by mistralaix** [android/performance-samples#254]
Using this version of the macrobenchmark library:
`implementation("androidx.benchmark:benchmark-macro-junit4:1.2.0-beta05")`

I get this error at the end of the benchmark (everything is going well during it):
```
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.test.benchmark/files/test_data/ExampleStartupBenchmark_startUpCompilationModePartial_iter000_2023-10-06-17-39-06.perfetto-trace (No such file or directory)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:308)
at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
at kotlin.io.FilesKt__FileReadWriteKt.appendBytes(FileReadWrite.kt:115)
at androidx.benchmark.perfetto.PerfettoCaptureWrapper.record(PerfettoCaptureWrapper.kt:140)
at androidx.benchmark.perfetto.PerfettoCaptureWrapper.record$default(PerfettoCaptureWrapper.kt:92)
at androidx.benchmark.macro.MacrobenchmarkKt$macrobenchmark$measurements$1.invoke(Macrobenchmark.kt:256)
at androidx.benchmark.macro.MacrobenchmarkKt$macrobenchmark$measurements$1.invoke(Macrobenchmark.kt:241)
at androidx.benchmark.perfetto.PerfettoTraceProcessor$Companion.runServer(PerfettoTraceProcessor.kt:105)
at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmark(Macrobenchmark.kt:241)
at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmarkWithStartupMode(Macrobenchmark.kt:415)
at androidx.benchmark.macro.junit4.MacrobenchmarkRule.measureRepeated(MacrobenchmarkRule.kt:107)
at com.test.benchmark.ExampleStartupBenchmark.startup(ExampleStartupBenchmark.kt:67)
at com.test.benchmark.ExampleStartupBenchmark.startUpCompilationModePartial(ExampleStartupBenchmark.kt:49)
```

Here are the logs prior to the error:
```
Writing to /storage/emulated/0/Android/data/com.test.benchmark/cache/ExampleStartupBenchmark_startUpCompilationModePartial_iter000_2023-10-06-17-39-06.perfetto-trace.

Moving /storage/emulated/0/Android/data/com.test.benchmark/cache/ExampleStartupBenchmark_startUpCompilationModePartial_iter000_2023-10-06-17-39-06.perfetto-trace to /storage/emulated/0/Android/data/com.test.benchmark/files/test_data/ExampleStartupBenchmark_startUpCompilationModePartial_iter000_2023-10-06-17-39-06.perfetto-trace

stopserver
Perfetto trace processor shell server stopped (pid=16707).
```

If I try to run the macrobenchmark using the version `1.1.1` of the library, I get the error described in this issue:
#137 Unable to read any metrics during benchmark

I am running the benchmark on a rooted device with Android API 28.

Here's my benchmark code:
``` kotlin
fun startup(mode: CompilationMode) = benchmarkRule.measureRepeated(
        packageName = APP_PACKAGE_NAME,
        metrics = listOf(StartupTimingMetric()),
        iterations = 1,
        startupMode = StartupMode.WARM,
        compilationMode = mode,
        setupBlock = {
            allowPermissions()
            pressHome()
        }
    ) {
        startActivityAndWait()
        testScenario()
    }
```

**Comment by keyboardsurfer** [comment]
I can't reproduce this issue with the `1.2.0-rc01` version of macrobenchmark. Please verify the issue still exists.

**Comment by keyboardsurfer** [comment]
We need your input to act on this issue.
This issue will be closed soon unless there is further actionable input.
