### ISSUE TITLE
Why does the startupCompilationBaselineProfiles test fail with IllegalStateException on my OPPO A53 (Android 12)?

### ISSUE THREAD

**Issue by RodionShulik** [android/performance-samples#302]
I'm running the following benchmark test on an **Android 12 ColorOS 12.1 OPPO A53** device:

```kotlin
package com.google.baselineprofile

import androidx.benchmark.macro.BaselineProfileMode
import androidx.benchmark.macro.CompilationMode
import androidx.benchmark.macro.StartupMode
import androidx.benchmark.macro.StartupTimingMetric
import androidx.benchmark.macro.junit4.MacrobenchmarkRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.filters.LargeTest
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
@LargeTest
class StartupBenchmarks {

    @get:Rule
    val rule = MacrobenchmarkRule()

    @Test
    fun startupCompilationNone() =
        benchmark(CompilationMode.None())

    @Test
    fun startupCompilationBaselineProfiles() =
        benchmark(CompilationMode.Partial(BaselineProfileMode.Require))

    private fun benchmark(compilationMode: CompilationMode) {
        rule.measureRepeated(
            packageName = "com.example.baselineprofiles_codelab",
            metrics = listOf(StartupTimingMetric()),
            compilationMode = compilationMode,
            startupMode = StartupMode.COLD,
            iterations = 10,
            setupBlock = {
                pressHome()
            },
            measureBlock = {
                startActivityAndWait()
                waitForAsyncContent()
            }
        )
    }
}
```

On my OPPO A53, the test `startupCompilationBaselineProfiles` fails with the following error: 

```
java.lang.IllegalStateException: Failed to compile (out=Error: Failed to compile !)
    at androidx.benchmark.macro.CompilationMode$Companion.cmdPackageCompile$benchmark_macro_release(CompilationMode.kt:434)
    at androidx.benchmark.macro.CompilationMode$Partial.compileImpl$benchmark_macro_release(CompilationMode.kt:307)
    at androidx.benchmark.macro.CompilationMode.resetAndCompile$benchmark_macro_release(CompilationMode.kt:114)
    at androidx.benchmark.macro.CompilationMode.resetAndCompile$benchmark_macro_release$default(CompilationMode.kt:75)
    at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmark(Macrobenchmark.kt:237)
    at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmarkWithStartupMode(Macrobenchmark.kt:436)
    at androidx.benchmark.macro.junit4.MacrobenchmarkRule.measureRepeated(MacrobenchmarkRule.kt:107)
    at com.google.baselineprofile.StartupBenchmarks.benchmark(StartupBenchmarks.kt:49)
```

However, the `startupCompilationNone` test runs successfully on the same device. When I run both tests on other devices, they work correctly without errors.

### Additional Context:
- **Device:** OPPO A53
- **OS Version:** Android 12 (ColorOS 12.1)
- **Erroring Test:** `startupCompilationBaselineProfiles`
- **Working Test:** `startupCompilationNone`

### Question:
Why does this issue occur on my OPPO A53 device? Is there something specific to this device or ColorOS that causes the `CompilationMode.Partial` test to fail? How can I fix or work around this problem?

**Comment by keyboardsurfer** [comment]
You have already asked this as a question on [StackOverflow](https://stackoverflow.com/questions/79243858/why-does-the-startupcompilationbaselineprofiles-test-fail-with-illegalstateexcep). Closing this issue as duplicate.
