### ISSUE TITLE
!!! JUnit version 3.8 or later expected:

### ISSUE THREAD

**Issue by IamVigneshG** [android/performance-samples#41]
getting this error even after all work arounds
https://github.com/android/performance-samples/issues/24 - not working 

!!! JUnit version 3.8 or later expected:

java.lang.ClassNotFoundException: junit.framework.ComparisonFailure
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.junit.JUnitStarter.junitVersionChecks(JUnitStarter.java:221)
	at com.intellij.rt.execution.junit.JUnitStarter.canWorkWithJUnitVersion(JUnitStarter.java:207)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:61)

**Comment by ChrisCraik** [comment]
This is a Studio issue, see https://issuetracker.google.com/issues/132969582#comment3.

That comment explains how to report it to Android Studio (please include a sample project in this state if possible), and a workaround when this occurs.

**Comment by IamVigneshG** [comment]
Once I did that workaround, I am getting this error 
    java.lang.RuntimeException: Unable to instantiate instrumentation ComponentInfo{com.myapp.test.benchmark.test/androidx.benchmark.junit4.AndroidBenchmarkRunner}: java.lang.ClassNotFoundException: Didn't find class "androidx.benchmark.junit4.AndroidBenchmarkRunner" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.myapp.test.benchmark.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.test.benchmark.test-1/lib/arm64, /system/lib64, /vendor/lib64]]

**Comment by Dhananjay1992** [comment]
If you have updated android studio version to 4.1 wiuth latest gradle plygin. Please comment out

//    useLibrary 'android.test.runner'
It will fix error for you.
