### ISSUE TITLE
TrivialStartupBenchmark always failed for StartupMode.WARM and StartupMode.HOT

### ISSUE THREAD

**Issue by devarafikry** [android/performance-samples#90]
TrivialStartupBenchmark always failed for StartupMode.WARM and StartupMode.HOT. Also I noticed that all startup mode benchmark is working fine in androidx.benchmark:benchmark-macro-junit4:1.1.0-alpha02, but starting in androidx.benchmark:benchmark-macro-junit4:1.1.0-alpha05 the HOT and WARM startup mode always failed.

Error logs:
java.lang.IllegalArgumentException: Unable to read any metrics during benchmark (metric list: [androidx.benchmark.macro.StartupTimingMetric@b5f2a80]).
Check that you're performing the operations to be measured. For example, if
using StartupTimingMetric, are you starting an activity for the specified package
in the measure block?
	at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmark(Macrobenchmark.kt:198)
	at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmarkWithStartupMode(Macrobenchmark.kt:259)
	at androidx.benchmark.macro.junit4.MacrobenchmarkRule.measureRepeated(MacrobenchmarkRule.kt:68)
	at androidx.benchmark.macro.junit4.MacrobenchmarkRule.measureRepeated$default(MacrobenchmarkRule.kt:58)
	at com.example.macrobenchmark.StartupUtilsKt.measureStartup(StartupUtils.kt:32)
	at com.example.macrobenchmark.TrivialStartupBenchmark.startup(TrivialStartupBenchmark.kt:34)

**Comment by iamritav** [comment]
I too am getting `TrivialStartupBenchmark` failing all the time for StartupMode.WARM  with the same error.

**Comment by keyboardsurfer** [comment]
This discussion seems to be resolved and I'm closing this issue. If you encounter issues with the sample or library in the future, please open a [new issue](new).
